import { readFileSync } from 'fs';
import { resolve } from 'path';

interface TestUser {
  userId: string;
  email: string;
  name: string;
  role: string;
  token: string;
}

/**
 * Load test users from users.json file
 * This file is generated by: npm run db:seed
 */
export function loadTestUsers(): { admin: TestUser; user: TestUser } {
  try {
    const usersJsonPath = resolve(__dirname, '../../users.json');
    const usersData = JSON.parse(readFileSync(usersJsonPath, 'utf8'));

    const admin = usersData.find(
      (u: TestUser) => u.role === 'ADMIN' || u.email === 'admin@catalog.com',
    );
    const user = usersData.find(
      (u: TestUser) =>
        u.role === 'REGULAR' || u.email === 'user@catalog.com',
    );

    if (!admin || !user) {
      throw new Error(
        'Could not find admin or user in users.json. Run: npm run db:seed',
      );
    }

    return { admin, user };
  } catch (error) {
    console.error('Failed to load test users from users.json');
    console.error('Make sure to run: npm run db:seed');
    throw error;
  }
}
